name: first_aid_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  carousel_slider: ^4.2.1
  geolocator: ^8.0.5
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^3.5.7
  geocoding: ^2.1.0
  location: ^5.0.3
  permission_handler: ^10.4.5
  geolocator_platform_interface: ^4.0.8
  cloud_firestore: ^4.9.1
  get: ^4.6.6
  firebase_helpers: ^0.6.1
  shared_preferences: ^2.2.1
  transparent_image: ^2.0.1
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  flutter_native_image: ^0.0.6+1
  image_picker: ^1.0.4
  firebase_database: ^10.2.5
  fluttertoast: ^8.2.2
  flutter_linkify: ^6.0.0
  photo_view: ^0.14.0
  url_launcher: ^6.1.14
  google_fonts: ^5.1.0
  csc_picker: ^0.2.7
  google_nav_bar: ^5.0.6
  flutter_phone_direct_caller: ^2.1.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter 
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
    - family: Nunito
      fonts: 
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoLight.ttf
          weight: 300
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800

